### PR TITLE
L10n fr

### PR DESCRIPTION
**Pull request by tdd**
Hey @maxogden! How are you?

First, thanks for this workshopper, it's pretty cool (although I'd love to see the exercises alluded to in the original screenshot!).

As part of the nodeschool/organizers#64 g11n effort currently underway, I'm bringing all workshopper-based workshops up to snuff on the latest versions of it so they can get translated (L10n) readily.

I'm also bringing them on the latest versions of their tested libs, and re-testing all the exercises, to reduce the risk of obsolescence.

This PR both upgrades the infra and provides FR L10n with third-party proofreading already baked in. I hope you see this favorably. We're hosting regular Paris NodeSchool sessions, and it would be fantastic if this could all be merged in and bumped in npm soon :smile:

I am, of course, available for all questions and discussions on this.

Best,

_(Unrelated: you use mostly the `docs/nnode-api-docs.html#all_buffer` link in the problem texts, except for one where you use `node_apidoc/buffer.html`, which makes more sense in the context of this workshop. On the other hand, bundling in all the other Node API pages doesn't make much sense, does it (perhaps a couple are cross-linked from buffer's, but that's it). Shouldn't we use a single link target across all problems, probably the buffer page's one?)_

### CODE REVIEW

**Comment by tdd** [comment]
Incidentally, this closes #21 along the way :wink:

**Comment by maxogden** [comment]
woot thanks!

**Comment by max-mapper** [comment]
i've tested and published to npm as 2.1.0. i also added you as an owner so you can merge PRs and publish to npm when necessary. thanks for the PR!

**Comment by tdd** [comment]
Hey Max,

'Most welcome :smile: Thanks for the merge and publish!

**Pull request merged**
